version: "1"

services:
  cloudservice:
    image: 'cloudservice:1.0'
    ports:
      - 8080
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/diploma
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "pda"


  database:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pda
      - POSTGRES_DB=diploma